apps/supermercado/urls.py
from django.urls import path

from .views.supermercado_create import SupermercadoCreateView
from .views.supermercado_delete import SupermercadoDeleteView
from .views.supermercado_detail import SupermercadoDetailView
from .views.supermercado_detail_categoria import SupermercadoCategoriaView
from .views.supermercado_detail_promocao import SupermercadoPromocaoView
from .views.supermercado_detail_usuario import SupermercadoUsuarioDetailView
from .views.supermercado_list import SupermercadoListView
from .views.supermercado_update import SupermercadoUpdateView

urlpatterns = [
    path("list", SupermercadoListView.as_view(), name="supermercado_list"),
    path("cad", SupermercadoCreateView.as_view(), name="supermercado_create"),
    path(
        "update/<int:pk>/",
        SupermercadoUpdateView.as_view(),
        name="supermercado_update",
    ),
    path(
        "detail/<int:pk>/",
        SupermercadoDetailView.as_view(),
        name="supermercado_detail",
    ),
    path(
        "delete/<int:pk>/",
        SupermercadoDeleteView.as_view(),
        name="supermercado_delete",
    ),
    path(
        "detailusuario/<int:pk>/",
        SupermercadoUsuarioDetailView.as_view(),
        name="supermercado_detail_usuario",
    ),
    path(
        "supermercado_categoria/<int:pk>/",
        SupermercadoCategoriaView.as_view(),
        name="supermercado_categoria",
    ),
    path(
        "supermercado_promocao/<int:pk>/",
        SupermercadoPromocaoView.as_view(),
        name="supermercado_promocao",
    ),
]

integrador/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)
from rest_framework import routers
from rest_framework.authtoken import views

main_router = routers.DefaultRouter()

handler403 = "core.views.handler403.handler403"
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("usuario/", include("usuario.urls")),
    path("supermercado/", include("supermercado.urls")),
    path("produto/", include("produto.urls")),
    path("promocao/", include("promocao.urls")),
    path("", include("django.contrib.auth.urls")),
    path("accounts/", include("allauth.urls")),
    # api
    # YOUR PATTERNS
    path("api/-token-auth/", views.obtain_auth_token),
    path("api/", include(main_router.urls)),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    # Optional UI:
    path(
        "api/schema/swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path(
        "api/schema/redoc/",
        SpectacularRedocView.as_view(url_name="schema"),
        name="redoc",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/produto/models/categoria.py
from django.db import models
from django.urls import reverse


class Categoria(models.Model):
    nome = models.CharField(max_length=100, verbose_name="Categoria")

    supermercados = models.ForeignKey(
        "supermercado.Supermercado",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )

    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"
        ordering = ["nome"]

    def __str__(self):
        return self.nome

    @property
    def get_absolute_url(self):
        return reverse("categoria_update", args=[str(self.id)])

    @property
    def get_delete_url(self):
        return reverse("categoria_delete", args=[str(self.id)])

apps/produto/models/produto.py
from django.db import models
from django.urls import reverse


class Produto(models.Model):

    nome = models.CharField(verbose_name="Produto", max_length=100)
    valor = models.DecimalField(
        verbose_name="Valor", max_digits=10, decimal_places=2, default=0
    )
    estoque = models.IntegerField(verbose_name="Estoque")
    imagem = models.ImageField(
        verbose_name="Imagem", upload_to="produto/produtos/"
    )
    descricao = models.TextField(verbose_name="Descrição", blank=True)
    criado = models.DateTimeField(verbose_name="Criado em", auto_now_add=True)
    modificado = models.DateTimeField("Modificado em", auto_now=True)

    categorias = models.ManyToManyField(
        "Categoria", verbose_name="Categorias", blank=True
    )
    supermercados = models.ForeignKey(
        "supermercado.Supermercado",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    promocao = models.ForeignKey(
        "promocao.Promocao",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )

    class Meta:
        verbose_name = "Produto"
        verbose_name_plural = "Produtos"
        ordering = ["nome"]

    def __str__(self):
        return self.nome

    @property
    def get_absolute_url(self):
        return reverse("produto_update", args=[str(self.id)])

    @property
    def get_delete_url(self):
        return reverse("produto_delete", args=[str(self.id)])

apps/promocao/models/promocao.py
from django.db import models
from django.urls import reverse


class Promocao(models.Model):
    nome = models.CharField(max_length=100, verbose_name="Promoção")

    supermercados = models.ForeignKey(
        "supermercado.Supermercado",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )

    class Meta:
        verbose_name = "Promoção"
        verbose_name_plural = "Promoções"
        ordering = ["nome"]

    def __str__(self):
        return self.nome

    @property
    def get_absolute_url(self):
        return reverse("promocao_update", args=[str(self.id)])

    @property
    def get_delete_url(self):
        return reverse("promocao_delete", args=[str(self.id)])

apps/supermercado/models/supermercado.py
from django.db import models
from django.urls import reverse


class Supermercado(models.Model):
    nome = models.CharField(verbose_name="Nome", max_length=100)
    imagem = models.ImageField(
        null=True,
        verbose_name="Imagem",
        upload_to="supermercado/supermercados/",
    )
    cpf = models.CharField(verbose_name="CPF", max_length=11)
    cnpj = models.CharField(verbose_name="CNPJ", max_length=14)
    cep = models.CharField(verbose_name="CEP", max_length=11)
    cidade = models.CharField(verbose_name="Cidade", max_length=100)
    bairro = models.CharField(verbose_name="Bairro", max_length=11)
    rua = models.CharField(verbose_name="Rua", max_length=100)
    numero = models.IntegerField(verbose_name="Número")
    date_joined = models.DateTimeField("Data de Entrada", auto_now_add=True)

    usuario = models.ForeignKey(
        "usuario.Usuario", on_delete=models.CASCADE, null=True, blank=True
    )

    def __str__(self):
        return self.nome

    class Meta:
        app_label = "supermercado"
        verbose_name = "Supermercado"
        verbose_name_plural = "Supermercados"

    @property
    def get_absolute_url(self):
        return reverse("supermercado_update", args=[str(self.id)])

    @property
    def get_delete_url(self):
        return reverse("supermercado_delete", args=[str(self.id)])

apps/supermercado/forms/supermercado_create_form.py
from crum import get_current_user
from django import forms
from supermercado.models.supermercado import Supermercado


class SupermercadoForm(forms.ModelForm):
    class Meta:
        model = Supermercado

        fields = [
            "nome",
            "cnpj",
            "cpf",
            "cep",
            "cidade",
            "bairro",
            "rua",
            "numero",
            "imagem",
            "usuario",
        ]

    def __init__(self, *args, **kwargs):
        super(SupermercadoForm, self).__init__(*args, **kwargs)
        self.initial["usuario"] = get_current_user().id
        # self.fields["usuario"].widget.attrs["disabled"] = True

apps/supermercado/views/supermercado_create.py
from django.views.generic import CreateView
from rolepermissions.mixins import HasRoleMixin

from apps.supermercado.forms.supermercado_create_form import SupermercadoForm
from utils.decorators import LoginRequiredMixin

from ..models.supermercado import Supermercado


class SupermercadoCreateView(HasRoleMixin, LoginRequiredMixin, CreateView):
    model = Supermercado
    allowed_roles = "administrador"

    def get_queryset(self):
        usuario = self.request.user.id

        return Supermercado.objects.filter(usuario=usuario)

    form_class = SupermercadoForm

    success_url = "list"

apps/supermercado/views/supermercado_delete.py
from django.views.generic import DeleteView
from rolepermissions.mixins import HasRoleMixin
from supermercado.models.supermercado import Supermercado

from utils.decorators import LoginRequiredMixin


class SupermercadoDeleteView(HasRoleMixin, LoginRequiredMixin, DeleteView):
    model = Supermercado
    allowed_roles = "administrador"
    success_url = "/dashboard"

apps/supermercado/views/supermercado_detail.py
from django.core.paginator import Paginator
from django.shortcuts import render
from django.views.generic import DetailView
from produto.models.produto import Produto
from supermercado.models.supermercado import Supermercado

from utils.decorators import LoginRequiredMixin


class SupermercadoDetailView(LoginRequiredMixin, DetailView):
    model = Supermercado

    template_name = "supermercado/supermercado_detail.html"
    paginate_by = 1

    def supermercado_detail_view(request, id):
        supermercado = Supermercado.objects.get(id=id)
        # url = reverse("supermercado_detail", args=(id,))
        context = {"supermercado": supermercado}
        return render(request, context)

apps/supermercado/views/supermercado_detail_categoria.py
from django.shortcuts import render
from django.views.generic import DetailView
from rolepermissions.mixins import HasRoleMixin
from supermercado.models.supermercado import Supermercado

from utils.decorators import LoginRequiredMixin


class SupermercadoCategoriaView(HasRoleMixin, LoginRequiredMixin, DetailView):
    model = Supermercado
    allowed_roles = "administrador"
    template_name = "supermercado/supermercado_detail_categoria.html"

    def supermercado_detail_view(request, id):
        supermercado = Supermercado.objects.get(id=id)
        # url = reverse("supermercado_detail", args=(id,))
        context = {"supermercado": supermercado}
        return render(request, context)

apps/supermercado/views/supermercado_detail_promocao.py
from django.shortcuts import render
from django.views.generic import DetailView
from rolepermissions.mixins import HasRoleMixin
from supermercado.models.supermercado import Supermercado

from utils.decorators import LoginRequiredMixin


class SupermercadoPromocaoView(HasRoleMixin, LoginRequiredMixin, DetailView):
    model = Supermercado
    allowed_roles = "administrador"
    template_name = "supermercado/supermercado_detail_promocao.html"

    def supermercado_detail_view(request, id):
        supermercado = Supermercado.objects.get(id=id)
        # url = reverse("supermercado_detail", args=(id,))
        context = {"supermercado": supermercado}
        return render(request, context)

apps/supermercado/views/supermercado_detail_usuario.py
from django.shortcuts import render
from django.views.generic import DetailView
from supermercado.models.supermercado import Supermercado

from utils.decorators import LoginRequiredMixin


class SupermercadoUsuarioDetailView(LoginRequiredMixin, DetailView):
    model = Supermercado

    template_name = "supermercado/supermercado_detail_usuario.html"

    def supermercado_detail_usuario_view(request, id):
        supermercados = Supermercado.objects.get(id=id)
        # url = reverse("supermercado_detail", args=(id,))
        context = {"supermercados": supermercados}
        return render(request, context)

apps/supermercado/views/supermercado_list.py
from django.views.generic import ListView
from supermercado.models.supermercado import Supermercado

from utils.decorators import LoginRequiredMixin


class SupermercadoListView(LoginRequiredMixin, ListView):
    model = Supermercado

    def supermercado(self):

        super = Supermercado.objects.all()

        return super

apps/supermercado/views/supermercado_update.py
from django.views.generic import UpdateView
from rolepermissions.mixins import HasRoleMixin
from supermercado.models.supermercado import Supermercado

from utils.decorators import LoginRequiredMixin


class SupermercadoUpdateView(HasRoleMixin, LoginRequiredMixin, UpdateView):
    model = Supermercado
    allowed_roles = "administrador"
    fields = [
        "nome",
        "imagem",
        "cpf",
        "cnpj",
        "cep",
        "cidade",
        "bairro",
        "rua",
        "numero",
        "usuario",
    ]
    success_url = "/dashboard"

apps/supermercado/templates/supermercado/supermercado_confirm_delete.html
{% extends "admin_base.html" %}
{% load bootstrap5 %}
{% block title %}
  Confirmação de exclusão
{% endblock %}
{% load static %}

{% block 'head' %}
<link href="{% static 'supermercado/supermercado.css' %}" rel="stylesheet">
<!-- <script src="{% static 'js/admin.js' %}"></script> -->
{% endblock %}


{% block 'body' %}

<div class="container confirma">
  <form action="" method="post">
    {% csrf_token %}
    <div class="">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Você tem certeza que deseja deletar esse supermercado?</h5>
          {% buttons submit='Confirmar' %}
            {% bootstrap_button content='Cancelar' href="javascript:history.go(-1);" button_type='link' button_class='btn btn-default' size='md' %}
          {% endbuttons %}
        </div>
      </div>
    </div>
  </form>
</div>
           
<!-- 
<h1><Excluir</h1> -->


{% endblock%}

apps/supermercado/templates/supermercado/supermercado_detail.html
{% extends "admin_base.html" %}
{% load bootstrap5 %}

{% load static %}

{% block 'head' %}
<link href="{% static 'supermercado/supermercado.css' %}" rel="stylesheet">
<!-- <link href="{% static 'core/core.css' %}" rel="stylesheet"> -->
<!-- <script src="{% static 'js/admin.js' %}"></script> -->
{% endblock %}


{% block 'body' %}
<br>
<div class="title-super">
    <h3>Você está no: <b>{{supermercado.nome}}</b></h3>

    <a href="{%url 'produto_create'%}"><button type="button" class="btn btn-primary">Adicionar produto</button></a>
    <a href="{%url 'supermercado_categoria' supermercado.id%}"><button type="button" class="btn btn-primary">Categorias</button></a>
    <a href="{%url 'supermercado_promocao' supermercado.id%}"><button type="button" class="btn btn-primary">Promoções</button></a>
   
</div>
<!-- 
   

    

    <section>
        <div class="row">
            <div class="col-lg-3 mb-3 gallery">
                
                <div class="card card-header">
                    {%if supermercado.imagem%}
                        <img src="{{supermercado.imagem.url}}" class="card-img-top" alt="...">
                    {%endif%}
                    <div class="card-body">
                        <h5 class="card-title">Supermercado:{{supermercado.nome}}</h5>
                        <p class="card-text">Localização:{{supermercado.cidade}}, {{supermercado.bairro}}, {{supermercado.rua}}, {{supermercado.numero}}</p>
                    
                         -->
                        
                        <!-- <a href="" class="btn btn-outline-danger btn-sm"><i class="far fa-heart"></i></a> -->
                    <!-- </div>
                </div>
            </div>
            
        </div>
    </section>
</div> -->
<br>

<table>
    <thead>
      <tr>
        <th scope="col">Imagem</th>
        <th scope="col">Produto</th>
        <th scope="col">Valor</th>
        <th scope="col">Descrição</th>
        <th scope="col">Ação</th>
      </tr>
    </thead>
    {% for produto in supermercado.produto_set.all %}
    <tbody>
      <tr>
        <td class="img-product">
            {%if produto.imagem%}
                <img src="{{produto.imagem.url}}" class="card-img-top" alt="...">
            {%endif%}
        </td>
        <td data-label="Produto">{{produto.nome}}</td>
        <td data-label="Valor">{{produto.valor}} R$</td>
        <td data-label="Descrição">{{produto.descricao}}</td>
        <td data-label="Ação">
            <a href="{%url 'produto_update' produto.id%}" class="btn btn-outline-primary btn-sm">Editar</a>
            <a href="{%url 'produto_delete' produto.id%}" class="btn btn-outline-danger btn-sm">Excluír</a>
        </td>
      </tr>
    </tbody>
    {%endfor%}
  </table>


<!-- <div class="container">
    <h3 class="text-primary mb-5 mt-5">Produtos do seu supermercado</h3>
    <div class="row">
        {% for produto in supermercado.produto_set.all %}
      <div class="card-product">
        {%if produto.imagem%}
            <img src="{{produto.imagem.url}}" class="card-img-top" alt="...">
        {%endif%}
        <div class="card-content-product">
          <h5 class="card-title-product">{{produto.nome}}</h5>
          <p class="card-price-product">{{produto.valor}} R$</p>
          <p class="card-description-product"><b>Descrição:</b> {{produto.descricao}}</p>
          <a href="{%url 'produto_update' produto.id%}" class="btn btn-outline-primary btn-sm">Edita</a>
        </div>
        <br>
      </div>
      {%endfor%}
      </div>
  </div> -->

{% endblock%} -->

apps/supermercado/templates/supermercado/supermercado_detail_categoria.html
{% extends "admin_base.html" %}

{% load bootstrap5 %}



{% load static %}

{% block 'head' %}
<link href="{% static 'supermercado/supermercado.css' %}" rel="stylesheet">
{% endblock %}


{% block 'body' %}

<div class="container">
    <br>
    <h3 class="text-primary mb-5 mt-5">Categorias do {{supermercado.nome}}</h3>
    <div class=" bg-side sidebar">
        <a href="{%url 'categoria_create'%}"><button type="button" class="btn btn-primary">Nova categoria</button></a>
    </div>
    <br>
    <section>
        <div class="row">
            {% for c in supermercado.categoria_set.all %}
            <div class="col-lg-3 mb-3 gallery">
                
                <div class="card card-header">
                    <div class="card-body">
                        <h5 class="card-title">Categoria: {{c.nome}}</h5> 
                        <a href="{%url 'categoria_detail_admin' c.id%}" class="btn btn-outline-primary btn-sm">Ver categoria</a>
                        <a href="{%url 'categoria_update' c.id%}" class="btn btn-outline-primary btn-sm">Editar</a>
                        <a href="{%url 'categoria_delete' c.id%}" class="btn btn-outline-danger btn-sm">Excluír</a>
                    </div>
                </div>
            </div>
            {%endfor%}
        </div>
    </section>
</div>











    

    

{%endblock%}

apps/supermercado/templates/supermercado/supermercado_detail_promocao.html
{% extends "admin_base.html" %}

{% load bootstrap5 %}



{% load static %}

{% block 'head' %}
<link href="{% static 'supermercado/supermercado.css' %}" rel="stylesheet">
{% endblock %}


{% block 'body' %}

<div class="container geral">
    <h3 class="text-primary mb-5 mt-5">Promoções do {{supermercado.nome}}</h3>
    <div class=" bg-side sidebar">
        <a href="{%url 'promocao_create'%}"><button type="button" class="btn btn-primary">Nova promoção</button></a>
    </div>
    <br>
    <section>
        <div class="row">
            {% for c in supermercado.promocao_set.all %}
            <div class="col-lg-3 mb-3 gallery">
                
                <div class="card card-header">
                    <div class="card-body">
                        <h5 class="card-title">Promoção: {{c.nome}}</h5> 
                        <a href="{%url 'promocao_detail_admin' c.id%}" class="btn btn-outline-primary btn-sm">Ver promoção</a>
                        <a href="{%url 'promocao_update' c.id%}" class="btn btn-outline-primary btn-sm">Editar</a>
                        <a href="{%url 'promocao_delete' c.id%}" class="btn btn-outline-danger btn-sm">Excluír</a>
                    </div>
                </div>
            </div>
            {%endfor%}
        </div>
    </section>
</div>











    

    

{%endblock%}

apps/supermercado/templates/supermercado/supermercado_detail_usuario.html
{% extends "base.html" %}

{% load bootstrap5 %}



{% load static %}

{% block 'head' %}
<link href="{% static 'supermercado/supermercado.css' %}" rel="stylesheet">
{% endblock %}


{% block 'body' %}

<section class="container details">
    <h3 class="text-primary mb-5 mt-5">Informações do Supermercado</h3>
    <div class="d-block p-2">
        {%if supermercado.imagem%}
            <img src="{{supermercado.imagem.url}}" class="rounded mx-auto d-block" alt="...">
        {%endif%}

            <h5 class="card-title">Supermercado:{{supermercado.nome}}</h5>
            <p class="card-text"><b>Localização:</b> {{supermercado.cidade}}, {{supermercado.bairro}}, {{supermercado.rua}},
                {{supermercado.numero}}</p>
            <!-- <a href="" class="btn btn-outline-danger btn-sm"><i class="far fa-heart"></i></a> -->
      
    </div>
</section>

<br>







    
    <div class="container">
        <div class="row">
            {% for produto in supermercado.produto_set.all %}
          <div class="card-product">
            {%if produto.imagem%}
                <img src="{{produto.imagem.url}}" class="card-img-top" alt="...">
            {%endif%}
            <div class="card-content-product">
              <h5 class="card-title-product">{{produto.nome}}</h5>
              <p class="card-price-product">{{produto.valor}} R$</p>
            </div>
          </div>
          {%endfor%}
        </div>
      </div>

{% endblock%}

apps/supermercado/templates/supermercado/supermercado_form.html
{% extends "admin_base.html" %}
{% load bootstrap5 %}

{% load static %}

{% block 'head' %}
<link href="{% static 'core/core.css' %}" rel="stylesheet">
<!-- <script src="{% static 'js/admin.js' %}"></script> -->
{% endblock %}


{% block 'body' %}
                  
<br>
  <div class="container geral" >
    <h3 class="text-primary mb-5 mt-2">Adicionar supermercado</h3>
    <div class="form-style">
    <form method="post" enctype="multipart/form-data">
      {%csrf_token%}
      <!-- <form method="POST"> -->
        {%csrf_token%}
        <div class="">
          {{ form.non_field_errors }}
         
       
      
       </form> 
       {{ form.non_field_errors }}
      {% bootstrap_field form.nome %}
      {% bootstrap_field form.imagem %}
      {% bootstrap_field form.cpf %}
      {% bootstrap_field form.cnpj %}
      {% bootstrap_field form.cep %}
      {% bootstrap_field form.cidade %}
      {% bootstrap_field form.bairro %}
      {% bootstrap_field form.rua %}
      {% bootstrap_field form.numero %}
      <div style="pointer-events: none;">
        {% bootstrap_field form.usuario %}
      </div>
      {% buttons submit='Salvar' %} {% endbuttons %}
    </form> 
  </div>
  </div>            
</div>


{% endblock%}

apps/supermercado/templates/supermercado/supermercado_list.html
{% extends "base.html" %}

{% load bootstrap5 %}



{% load static %}

{% block 'head' %}
<link href="{% static 'supermercado/supermercado.css' %}" rel="stylesheet">
{% endblock %}


{% block 'body' %}

<div class="container geral">
    <h3 class="text-primary mb-5 mt-5">Supermercados</h3>

    <div class="container">
        <div class="row">
            {%for super in object_list %}
                <div class="card card-super">
                    {%if super.imagem%}
                        <img src="{{super.imagem.url}}" class="card-img-top" alt="...">
                    {%endif%}
                    <div class="card-content-product">
                        <h5 class="card-title">Supermercado:{{super.nome}}</h5>
                        <p class="card-text">Localização:{{super.cidade}}, {{super.bairro}}, {{super.rua}}, {{super.numero}}</p>
                    
                        
                        <a href="{%url 'supermercado_detail_usuario' super.id %}" class="btn btn-outline-primary btn-sm">Confira!</a>
                        <!-- <a href="" class="btn btn-outline-danger btn-sm"><i class="far fa-heart"></i></a> -->
                    </div>
                </div>
            
            {%endfor%}
        </div>
    </div>
</div>











    

    

{%endblock%}