apps/usuario/urls.py
from django.urls import path
from usuario.views.register_view import RegisterView
from usuario.views.usuario_list import UsuarioListView

app_name = "usuario"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("list/", UsuarioListView.as_view(), name="usuario_list"),
]

integrador/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)
from rest_framework import routers
from rest_framework.authtoken import views

main_router = routers.DefaultRouter()

handler403 = "core.views.handler403.handler403"
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("usuario/", include("usuario.urls")),
    path("supermercado/", include("supermercado.urls")),
    path("produto/", include("produto.urls")),
    path("promocao/", include("promocao.urls")),
    path("", include("django.contrib.auth.urls")),
    path("accounts/", include("allauth.urls")),
    # api
    # YOUR PATTERNS
    path("api/-token-auth/", views.obtain_auth_token),
    path("api/", include(main_router.urls)),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    # Optional UI:
    path(
        "api/schema/swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path(
        "api/schema/redoc/",
        SpectacularRedocView.as_view(url_name="schema"),
        name="redoc",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/produto/models/categoria.py
from django.db import models
from django.urls import reverse


class Categoria(models.Model):
    nome = models.CharField(max_length=100, verbose_name="Categoria")

    supermercados = models.ForeignKey(
        "supermercado.Supermercado",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )

    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"
        ordering = ["nome"]

    def __str__(self):
        return self.nome

    @property
    def get_absolute_url(self):
        return reverse("categoria_update", args=[str(self.id)])

    @property
    def get_delete_url(self):
        return reverse("categoria_delete", args=[str(self.id)])

apps/promocao/models/promocao.py
from django.db import models
from django.urls import reverse


class Promocao(models.Model):
    nome = models.CharField(max_length=100, verbose_name="Promoção")

    supermercados = models.ForeignKey(
        "supermercado.Supermercado",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )

    class Meta:
        verbose_name = "Promoção"
        verbose_name_plural = "Promoções"
        ordering = ["nome"]

    def __str__(self):
        return self.nome

    @property
    def get_absolute_url(self):
        return reverse("promocao_update", args=[str(self.id)])

    @property
    def get_delete_url(self):
        return reverse("promocao_delete", args=[str(self.id)])

templates/admin_base.html
{% load static %}
<!doctype html>
<html lang="pt-BR">

<head>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block 'title' %}{% endblock%}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css"
        integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">

    {% block 'head' %}{% endblock%}

    <link href="{% static 'css/admin.css'%}" rel="stylesheet">
    <script src="{% static 'js/admin.js' %}"></script>
</head>

<body id="body-pd">
    <header class="header" id="header">

        <div class="header_toggle"> <i class='bx bx-menu' id="header-toggle"></i> </div>

        <div class="header_img"> 
            <img src="https://i.imgur.com/hczKIze.jpg" alt="">
        </div>
    </header>
    <div class="l-navbar" id="nav-bar">
        <nav class="nav">
            <div> <a href="{%url 'home'%}" class="nav_logo"> <i class='bx bx-home nav_logo-icon'></i> <span class="nav_logo-name">menorPreço</span> </a>
                <div class="nav_list"> 
                    <a href="{%url 'dashboard'%}" class="nav_link active"> <i class='bx bx-grid-alt nav_icon'></i> <span class="nav_name">Dashboard</span> </a> 
                    <a href="{%url 'supermercado_create'%}" class="nav_link"> <i class='bx bx-cart md-cart'></i> <span class="nav_name">Supermercado</span> </a> 
                    <a href="#" class="nav_link"> <i class='bx bx-bookmark nav_icon'></i> <span class="nav_name">Produtos</span> </a> 
                    <a href="#" class="nav_link"> <i class='bx bx-folder nav_icon'></i> <span class="nav_name">Promoções</span> </a>
                    <a href="{%url 'usuario:usuario_list'%}" class="nav_link"> <i class='bx bx-user nav_icon'></i> <span class="nav_name">Usuário</span> </a>  
                    <div class="nav_link"> <span class="nav_name"></span> </div> </div>
                
                </div> 
                <a href="{%url 'logout' %}" class="nav_link"> <i class='bx bx-log-out nav_icon'></i> <span class="nav_name">Sair</span> </a>

        </nav>
    </div>
    {% block 'body' %}{% endblock %}


    <div class="footer-basic">
        <footer>
            <div class="social"><a href="#"><i class="icon ion-social-instagram"></i></a><a href="#"><i
                        class="icon ion-social-snapchat"></i></a><a href="#"><i
                        class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-facebook"></i></a>
            </div>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="#">Inicio</a></li>
                <li class="list-inline-item"><a href="#">Supermercados</a></li>
                <li class="list-inline-item"><a href="#">Produtos</a></li>
                <li class="list-inline-item"><a href="#">Promoções</a></li>
                <!-- <li class="list-inline-item"><a href="#"></a></li> -->
            </ul>
            <p class="copyright">#menorPreço © 2023</p>
        </footer>
    </div>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>

</body>

</html>

templates/base.html
{% load static %}
<!doctype html>
<html lang="pt-BR">

<head>
  <meta charset="utf-8">
  <link href="{% static 'css/base.css'%}" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block 'title' %}{% endblock%}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet">
  {% block 'head' %}{% endblock%}
</head>

<body>

  <div class="superNav border-bottom py-2 bg-light">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 centerOnMobile">
          {%if user.is_authenticated%}
          <span
            class="d-none d-lg-inline-block d-md-inline-block d-sm-inline-block d-xs-none me-3"><strong>Bem vindo(a). {{user}}</strong></span>
         
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 d-lg-block d-md-block-d-sm-block d-xs-none text-end">
          <span class="me-3"><i class="fa-solid fa-file  text-muted me-2"></i><a class="text-muted"
              href="{%url 'dashboard' %}">Acessar Admin</a></span>

          <span class="me-3"><i class="fa-solid fa-file  text-muted me-2"></i><a class="text-muted"
              href="{%url 'logout' %}">Sair</a></span>

          {%else%}
          <span class="me-3"><i class="fa-solid fa-file text-muted me-2"></i><a class="text-muted"
              href="{%url 'login' %}">Entrar</a></span>

          <span class="me-3"><i class="fa-solid fa-file  text-muted me-2"></i><a class="text-muted"
              href="{%url 'usuario:register' %}">Cadastre-se</a></span>

       
            </div>
        {%endif%}
      
      </div>

    </div>
  </div>
  </div>

  <nav class="navbar navbar-expand-lg bg-primary sticky-top navbar-dark p-3 shadow-sm">
    <div class="container nav-menu">
      <a class="navbar-brand" href="{%url 'home'%}"><i class="fa-solid fa-shop me-2"></i> <strong>menorPreço</strong></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class=" collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ms-auto ">
          <li class="nav-item">
            <a class="nav-link mx-2 text-uppercase active" aria-current="page" href="{%url 'home'%}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link mx-2 text-uppercase" href="{%url 'supermercado_list'%}">Supermercados</a>
          </li>
          <li class="nav-item">
            <a class="nav-link mx-2 text-uppercase" href="{%url 'categoria_list'%}">Categorias</a>
          </li>
          <li class="nav-item">
            <a class="nav-link mx-2 text-uppercase" href="{%url 'promocao_list'%}">Promoções</a>
          </li>
          <li class="nav-item">
            <a class="nav-link mx-2 text-uppercase" href="#">Sobre</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  {% block 'body' %}{% endblock %}

  


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>